### ISSUE TITLE
Consider dropping php-5.x version and Mcrypt extension

### ISSUE THREAD

**Issue by peter279k** [gpslab/base64uid#2]
As title, this package depends on the `Mcrypt` extension and `php-5.x` versions.

The `php-5.x` versions are not stable and inactive now.

The `Mcrypt` is not reliable and it's deprecated by `php-7.x` versions.

@peter-gribanov, what do you think about this?

Once this issue is approved, I will work on this :). Thanks.

**Comment by peter-gribanov** [comment]
Mcrypt is a fallback for PHP < 7.0
http://php.net/manual/en/function.random-int.php#119670

So far i do not plan to dropping support PHP 5 in this project.

**Comment by peter279k** [comment]
Hi @peter-gribanov, thanks for your quick reply.

I think we can consider using the `random_compat` package to replace the `mcrypt` extension.

It uses the pure PHP to implement the `random_int` and I think it can make sure that it's compatible with native `random_int` :).

Or we can consider following code snippets:

And it can be equivalent to native `random_int`. 

```php
function secure_rand( $min, $max ) {
    $diff = $max - $min;
    if ($diff < 0 || $diff > 0x7FFFFFFF) {
        throw new RuntimeException("Bad range");
    }
    $bytes = mcrypt_create_iv( 4, MCRYPT_DEV_URANDOM );

    // if mcrypt is not enabled on your server, you can use this
    //$bytes = openssl_random_pseudo_bytes( 4 );

    // if mbstring is not enabled, you can also use iconv_strlen
    if ($bytes === false || mb_strlen($bytes, '8bit') != 4) {
        throw new RuntimeException("Unable to get 4 bytes");
    }

    $ary = unpack("Nint", $bytes);
    $val = $ary['int'] & 0x7FFFFFFF;   // 32-bit safe
    $fp = $val / 2147483647.0; // convert to [0,1]
    // if you really need a type of int take this
    // return (int) round($fp * $diff) + $min;
    // otherwise it will return a float without decimal numbers
    return round($fp * $diff) + $min;
}
```

**Comment by peter-gribanov** [comment]
Ok. Let's try using `random_compat` polyfill.
